name: Python Linting and Type Checking
on: [ push, pull_request ]
jobs:
  formatcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: chartboost/ruff-action@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install mypy and dependencies
        run: python -m pip install mypy;
             mypy --install-types

      - name: Run mypy
        run: mypy .