name: Python Linting and Type Checking
on: [push, pull_request]

jobs:
  formatcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: KandidatENV
          auto-activate-base: false

      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        
      - name: Activate KandidatENV and Run mypy
        shell: bash -l {0}
        run: |
          conda activate KandidatENV
          mypy .